[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "0xRakkesh", email = "rakesh904664@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.3.16",
    "langchain-groq",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "tavily-python>=0.7.27",
    "uvicorn>=0.52.4",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
